/* ============================================================
   Ben's Shed — API client
   Base URL: https://value-screener.onrender.com
   ============================================================ */

export const API_BASE = 'https://value-screener.onrender.com'

/**
 * Generic fetcher — throws on non-2xx responses.
 * Applies a 25s timeout so Render cold-start hangs don't block forever.
 * The DataContext retry logic then re-fires the request automatically.
 */
async function apiFetch(path, options = {}, timeoutMs = 15000) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const res = await fetch(`${API_BASE}${path}`, {
      headers: { 'Content-Type': 'application/json' },
      signal: controller.signal,
      ...options,
    })
    if (!res.ok) {
      const text = await res.text()
      throw new Error(`${res.status} ${res.statusText}: ${text}`)
    }
    return res.json()
  } catch (e) {
    if (e.name === 'AbortError') throw new Error('Request timed out — server may be waking up')
    throw e
  } finally {
    clearTimeout(timer)
  }
}

/* ── Endpoints ──────────────────────────────────────────── */

/** GET /api/screener — returns { instruments: [...] } */
// 3-minute timeout: first run after a fresh deploy fetches 648 tickers from
// yfinance sequentially — can take 3–10 min. Subsequent requests hit the cache
// and return in <2s. We wait patiently and show a skeleton in the meantime.
export const getScreener = (forceRefresh = false) =>
  apiFetch(`/api/screener${forceRefresh ? '?refresh=true' : ''}`, {}, 180000)

/**
 * GET /api/briefing — returns { ok, briefing, age_hours, stale }
 * briefing contains: headline, macro, signal_summary, signals, opportunities,
 * watchlist, news_highlights, generated_at, date_str
 */
export const getBriefing = () => apiFetch('/api/briefing')

/**
 * POST /api/briefing/refresh
 * Lightweight refresh: re-fetches macro + news without a full universe scan.
 * Typically 5–20s. Returns same shape as getBriefing.
 */
export const refreshBriefing = () =>
  apiFetch('/api/briefing/refresh', { method: 'POST' }, 45000)

/**
 * GET /api/briefing/news?tickers=ABF.L,BP.L
 * Returns { ok, watchlist_news: [...], market_news: [...] }
 * watchlist_news: Yahoo Finance per-ticker, tagged by ticker
 * market_news: RSS headlines sorted by sentiment magnitude
 */
export const getBriefingNews = (tickers = []) =>
  apiFetch(
    `/api/briefing/news${tickers.length ? `?tickers=${tickers.map(encodeURIComponent).join(',')}` : ''}`,
    {},
    30000
  )

/** GET /api/signals — returns { signals: [...] } */
export const getSignals = () => apiFetch('/api/signals')

/** GET /api/watchlist — returns { watchlist: [...] } */
export const getWatchlist = () => apiFetch('/api/watchlist')

/**
 * POST /api/watchlist
 * Add a ticker to the watchlist.
 * @param {string} ticker  — Yahoo Finance ticker, e.g. "BP.L"
 * @param {string} [name]  — Display name (optional, backend may infer)
 */
export const addToWatchlist = (ticker, name) =>
  apiFetch('/api/watchlist', {
    method: 'POST',
    body:   JSON.stringify({ ticker, name }),
  })

/**
 * DELETE /api/watchlist/:ticker
 * Remove a ticker from the watchlist. Returns 404 if not found.
 * @param {string} ticker  — Yahoo Finance ticker, e.g. "BP.L"
 */
export const deleteFromWatchlist = (ticker) =>
  apiFetch(`/api/watchlist/${encodeURIComponent(ticker.toUpperCase())}`, {
    method: 'DELETE',
  })

/** GET /api/macro — returns macro data object */
export const getMacro = () => apiFetch('/api/macro')

/** GET /health — simple health check */
export const getHealth = () => apiFetch('/health')

/**
 * GET /api/deepdive?ticker=X
 * Returns { ok, ticker, instrument, thesis }
 * thesis is AI-generated by Claude on the server.
 * Uses a longer timeout (30s) to allow for AI generation.
 */
export const getDeepDive = (ticker) =>
  apiFetch(`/api/deepdive?ticker=${encodeURIComponent(ticker.toUpperCase())}`, {}, 30000)

/**
 * GET /api/price-history?ticker=X&period=P
 * Returns { ok, ticker, period, data: [{date, price}] }
 * period: 1mo | 3mo | 6mo | ytd | 1y | 5y
 */
export const getPriceHistory = (ticker, period = '1y') =>
  apiFetch(
    `/api/price-history?ticker=${encodeURIComponent(ticker.toUpperCase())}&period=${period}`,
    {},
    15000
  )

/**
 * GET /api/dividends?ticker=X
 * Returns dividend data + AI income analysis.
 * Cached server-side for 30 days.
 * { ok, ticker, from_cache, div_yield, five_year_avg_yield, last_dividend,
 *   last_ex_date, payment_frequency, dividends_per_year, payout_ratio,
 *   dividend_growth_3y, history, roe, summary, generated_at }
 */
export const getDividends = (ticker) =>
  apiFetch(`/api/dividends?ticker=${encodeURIComponent(ticker.toUpperCase())}`, {}, 30000)

/* ── Portfolio ───────────────────────────────────────────── */

/**
 * GET /api/portfolio
 * Returns { ok, count, holdings, summary }
 * Each holding contains user-supplied fields + server-computed P&L + full
 * scored instrument record.
 */
export const getPortfolio = () => apiFetch('/api/portfolio')

/**
 * POST /api/portfolio
 * Add or update (upsert) a holding.
 * @param {Object} holding
 * @param {string}  holding.ticker         — Yahoo Finance ticker, e.g. "AAPL" or "BP.L"
 * @param {number}  holding.shares         — Number of shares (fractional OK)
 * @param {number}  holding.avg_cost       — Average cost basis per share in `currency`
 * @param {string}  [holding.currency]     — ISO-4217 currency of avg_cost (default "USD")
 * @param {string}  [holding.account]      — Account label, e.g. "ISA", "SIPP", "IRA"
 * @param {string}  [holding.notes]        — Free-text notes / investment thesis
 * @param {number}  [holding.target_weight]— Target portfolio weight % for drift alerting
 */
export const upsertHolding = (holding) =>
  apiFetch('/api/portfolio', {
    method: 'POST',
    body:   JSON.stringify(holding),
  })

/**
 * DELETE /api/portfolio/:ticker
 * Remove a holding by ticker. Returns 404 if not found.
 */
export const deleteHolding = (ticker) =>
  apiFetch(`/api/portfolio/${encodeURIComponent(ticker.toUpperCase())}`, {
    method: 'DELETE',
  })
